#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -f &
nitrogen --restore &
$HOME/.config/polybar/launch.sh &
picom &
xsetroot -cursor_name left_ptr &
setxkbmap -model pc105 -layout us,ru -option grp:alt_shift_toggle & 

firefox &
telegram-desktop -startintray &
pavucontrol &

bspc rule -a Pavucontrol desktop='^7'
bspc rule -a Firefox desktop='^2'

bspc monitor -d 1 2 3 4 5 6 7 

bspc config window_gap 12
bspc config border_width 2

bspc config split_ratio 0.5

bspc config normal_border_color "#23252e"
bspc config active_border_color "#23252e"
bspc config focused_border_color "#f9f8fe"
bspc config presel_feedback_color "#23252e"

bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus_follows_pointer true
bspc config pointer_modifier    super

bspc config single_monocle           true
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config paddingless_monocle  true
